export const SEARCH_FOCUSED = 'header/SEARCH_FOCUSED'
export const SEARCH_BLUR = 'header/SEARCH_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSEENTER = 'header/MOUSEENTER'
export const MOUSELEAVE = 'header/MOUSELEAVE'
export const CHANGEPAGE = 'header/CHANGE_PAGE'